### ISSUE TITLE
Issue generation job exits without completing after failure

### ISSUE THREAD

**Issue by jczimskey** [benbalter/bulk-issue-creator#21]
### Describe the bug

If a repository in data.csv exists but does not allow for issue creation (issues turned off, repository is archived) [the job will fail at that point](https://github.com/jczimskey/bulk-issue-creator/actions/runs/8145982958/job/22263455125#step:3:13). Any issues in repositories before that are created, but the job exits and does not create any further issues.

I noticed that in [the test run](https://github.com/jczimskey/bulk-issue-creator/actions/runs/8146025417/job/22263604625#step:3:64), scenarios where repositories simply do not exist seem to proceed with a warning just fine.

### Steps to reproduce the behavior

1. Use a data.csv file with a repository that exists but is not able to create an issue
2. Note in [the logs ](https://github.com/jczimskey/bulk-issue-creator/actions/runs/8145982958/job/22263455125#step:3:13)the failure, and that no subsequent issues are created

### Expected behavior

The job should fail entirely or repositories should be noted in the logs, but the job should continue.

**Comment by benbalter** [comment]
[The check for repo existence](https://github.com/benbalter/bulk-issue-creator/blob/main/src/bulk-issue-creator.ts#L194-L204) gracefully handles request errors. 

We should wrap the API call in `createIssues` and `createComments` to catch and warn on request errors, so that one buggy repo doesn't halt the entire operation.
